import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { ClerkProvider } from '@clerk/nextjs'


// eslint-disable-next-line @typescript-eslint/no-unused-vars
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          {/* 
            * The Provider component is added as deep as possible within the layout to optimize Next.js server/client.
            * This is because Next.js pre-renders the page on the server-side or statically at build time.
            * The deeper the Provider component is in the layout, the less likely it is to be included in the server-rendered HTML.
            * This reduces the size of the HTML and improves performance.
            */}
          <ClerkProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </ClerkProvider>
        </body>
      </html>
    </ClerkProvider >
    </>
  )
}